# NAリファレンスがある例
#<http://purl.jp/knapsack/activity#6724465cb1c0dadf66c0da7e20b93973>
#    sio:SIO_000255 <http://purl.jp/knapsack/annotation#b877c85460137f060ebabcbfb01b6a9a> ;
#    sio:SIO_001278 <http://www.knapsackfamily.com/BiologicalActivity/NA_dictionary.pdf> ;
#    a owl:Class ;
#    rdfs:label "Collagen protective", "Collagen protective"@en ;
#    rdfs:subClassOf mb:KNApSAcKBiologicalActivity ;
#    skos:altLabel "コラーゲン保護"@ja .
#<http://purl.jp/knapsack/annotation#86688c0f5ed07c1e7e20fa7098c36468>
#    mb:activity <http://purl.jp/knapsack/activity#087c278d491a13b3ce9871fcfffa0284>, <http://purl.jp/knapsack/activity#0f5035ac92125382fe2dd659a6db8e07>, <http://purl.jp/knapsack/activity#0fe08fc9bc6ae5c1b52cf51b0915d027>, <http://purl.jp/knapsack/activity#19f5243121de29e2ed89bcb9320222a2>, <http://purl.jp/knapsack/activity#2890caf75fcde34ff2a11431276e6b6f>, <http://purl.jp/knapsack/activity#2f98ef62f48d811287e63a0bf140b37f>, <http://purl.jp/knapsack/activity#353221b07f1d1d5273aa1d68b0e2a62d>, <http://purl.jp/knapsack/activity#3618ce6cb05c563859992e8fc0e90f19>, <http://purl.jp/knapsack/activity#429feaa506b847c1d225a970a015e529>, <http://purl.jp/knapsack/activity#445578b87bba4a0fe5eb2df65e40e962>, <http://purl.jp/knapsack/activity#4ffc243167106dff5f16c1248052d189>, <http://purl.jp/knapsack/activity#520e33fed5f677184f281652029baae2>, <http://purl.jp/knapsack/activity#565c77edf2850132160b3aaca84ac183>, <http://purl.jp/knapsack/activity#5f6ba7cae8a4042b2c60a0fdc32716ec>, <http://purl.jp/knapsack/activity#62fcc9f44ca7db58da6c271c426cc23d>, <http://purl.jp/knapsack/activity#6526527fb3b87ad8c86a79be758e5b76>, <http://purl.jp/knapsack/activity#6724465cb1c0dadf66c0da7e20b93973>, <http://purl.jp/knapsack/activity#67ab1176e9646ccc8a39716762de18d9>, <http://purl.jp/knapsack/activity#6dc5bd078ca290f7ff790ac5467804e5>, <http://purl.jp/knapsack/activity#7dfc456e7529ba9ff896d612d55fa84c>, <http://purl.jp/knapsack/activity#80a0f607c398b2c4f986d6bfec3e00a8>, <http://purl.jp/knapsack/activity#82dd036e078509059332e13f9c8c80fa>, <http://purl.jp/knapsack/activity#8c521461e4b3bb7afe67d84cddd0faa0>, <http://purl.jp/knapsack/activity#8f9f37d4df884f0c32058d794b09b119>, <http://purl.jp/knapsack/activity#990ad2253c947e629d1f348d25b1b3f4>, <http://purl.jp/knapsack/activity#9bed272783ec9181f09ccb2a6e8cd54f>, <http://purl.jp/knapsack/activity#9e5b2ebfb85c4cb6fdc385aee6d06c9e>, <http://purl.jp/knapsack/activity#a7c22fc08b37bb9fa087c7f966760dae>, <http://purl.jp/knapsack/activity#a9dd93686923d3b91b949c4a56e0cdbd>, <http://purl.jp/knapsack/activity#af8ef0d58868b1fe824dbe5cd5a383ce>, <http://purl.jp/knapsack/activity#b279ca377bb05a800f4674f495e6eada>, <http://purl.jp/knapsack/activity#b58f9b220e3ae53536479833f72139bd>, <http://purl.jp/knapsack/activity#b670e92ecc1809db2bfebaef1ba04c37>, <http://purl.jp/knapsack/activity#bb6c7ad79f52a130138721d92843389c>, <http://purl.jp/knapsack/activity#c01a4ad94b6437e2d9e98aa6add7c4f3>, <http://purl.jp/knapsack/activity#c238f0c3648364fd242078032a2b14ad>, <http://purl.jp/knapsack/activity#c4761310b015f968ca9aaddd783b1585>, <http://purl.jp/knapsack/activity#c6d309388d1fb27783c7a9516060b72d>, <http://purl.jp/knapsack/activity#c9ebd1f4a0a329c8e2b59427bc38f963>, <http://purl.jp/knapsack/activity#d3f8ce2efe6a5555b578a9be4be5124f>, <http://purl.jp/knapsack/activity#d9faa377e32cd84addeaba66b81e2258>, <http://purl.jp/knapsack/activity#da0d8fbce0fca3fbe177dd43d750b9c1>, <http://purl.jp/knapsack/activity#da2a205cdee6ce778d32c0832fef1d94>, <http://purl.jp/knapsack/activity#db85f1479a103ce01dc87806365ea574>, <http://purl.jp/knapsack/activity#dd6c2f16a92ed6e3373d9f26716cb4cd>, <http://purl.jp/knapsack/activity#e78cd994a0460ca2881dfe43333a91e4>, <http://purl.jp/knapsack/activity#e8512698c0dc49b07ba421edd80b1b66>, <http://purl.jp/knapsack/activity#ea40df624ba3da4c3209c3f4ef665475>, <http://purl.jp/knapsack/activity#f5ab667f9062c7abf508034f248a1865>, <http://purl.jp/knapsack/activity#f7efa0b030c2f0041d2e39d2eb6f8c30>, <http://purl.jp/knapsack/activity#fc9da20272f1c3e082ee535dd61c04d8> ;
#    mb:reference <http://purl.jp/knapsack/reference#9498058f7b9a417fa009c8dbc7ce48c3> ;
#    mb:sp "Vitis vinifera L." ;
#    a :KNApSAcKNaturalActivityAnnotation .
#    <http://purl.jp/knapsack/reference#9498058f7b9a417fa009c8dbc7ce48c3>
#    dc:title "James A. Duke,Handbook of Medicinal Herbs 2nd Ed.,CRC Press(2002)" ;
#    a mb:KNApSAcKReference 
- KnapsackBiologicalActivity mb:KnapsackBiologicalActivity:
  - rdf:type: owl:Class
  - rdfs:label: 
    - label_na_activity_root: '"(Obsolete)KnapsackBiologicalActivity"@en'  
  - sio:SIO_001278:
    - refers_to_na_dict: <http://www.knapsackfamily.com/BiologicalActivity/NA_dictionary.pdf>
- BiologicalActivity <http://purl.jp/knapsack/activity#2f98ef62f48d811287e63a0bf140b37f>:
  - rdf:type: owl:Class
  - rdfs:subClassOf:
    - na_subclassof: KnapsackBiologicalActivity
  - rdfs:label:
    - label_na_activity: '"Fragility", "Fragility"@en'
  - skos:altLabel:
    - skos_altlable_ja: '"虚弱"@ja'
  - sio:SIO_000255:
    - AnnotationNA
  - sio:SIO_001278:
    - refers_to_na: <http://www.knapsackfamily.com/MetaboliteActivity/MA_dictionary.pdf>
- AnnotationNA <http://purl.jp/knapsack/annotation#b877c85460137f060ebabcbfb01b6a9a>:
  - rdf:type: mb:KnapsackBiologicalActivityAnnotation
  - rdfs:label: 
    - label_na_anntation: "Vitis vinifera"
- KnapsackMetaboliteActivity mb:KnapsackMetaboliteActivity:
  - rdf:type: owl:Class
  - rdfs:label: 
    - label_ma_activity: '"(Obsolete)KnapsackMetaboliteActivity"@en'
  - sio:SIO_001278:
    - refers_to_ma_dict: <http://www.knapsackfamily.com/MetaboliteActivity/MA_dictionary.pdf>
- MetaboliteActivity <activity#e6114a598fe889c30e545c94477e309c>:
  - rdf:type: owl:Class
  - rdfs:subClassOf:
    - ma_subclassof: mb:KnapsackMetaboliteActivity
  - rdfs:label:
    - label_activity: '"exhibit alpha-amylase activity in aleurone"@en'
  - sio:SIO_000255:
    - AnnotationMA
  - sio:SIO_001278:
    - refers_to: <http://www.knapsackfamily.com/MetaboliteActivity/MA_dictionary.pdf>
- ReferenceMA <reference#0ed21477f86f5a0e270b3fccc668904a>:
  - rdf:type: mb:KNApSAcKReference
  - dc:title:
    - reference_ma_title: "Reeve,J.Exp.Bot.,25,(1974),431-445"
- AnnotationMA <annotation#d0a06d1c3e50afefc2a4136e3ad0001a>:
  - rdf:type: mb:KNApSAcKMetaboliteActivityAnnotation
  - mb:sp:
    - mb_sp: "Hordeum vulgare"
  - dcterms:isReferencedBy*:
    - annotation2_is_referenced_by: <reference#0ed21477f86f5a0e270b3fccc668904a>
- KNApSAcKCoreRecord <http://purl.jp/knapsack/C00000001>:
  - rdf:type:
    - mb:KNApSAcKCoreRecord
    - mb:KNApSAcKMetaboliteRecord
  - mb:category:
    - mb_category: "Enhance plant growth"
  - mb:function:
    - mb_function: "exhibit alpha-amylase activity in aleurone"
  - mb:targetsp:
    - mb_targetsp: "Hordeum vulgare"
  - mb:has-activity: MetaboliteActivity
  - dc:identifier:
    - knapsack_id: "C00000001"
  - rdfs:label:
    - rdfs_label: "Gibberellin A1;GA1"
  - mb:fid:
    - knapsack_fid: "C19H24O6_C00000001"
  - foaf:homepage:
    - foaf_homepage: <https://mb.metabolomics.jp/wiki/Compound:C00000001>
  - rdfs:seeAlso:
    - rdfs_seealso: <http://www.knapsackfamily.com/knapsack_core/info.php?sname=C_ID&word=C00000001>
  - sio:SIO_000008+: #sio:has-attribute
    - MolecularFormula
    - Names
    - MolecularWeight     
  - dc:hasPart+:
    - MolFile
    - ChemDraw
    - Gif
  - cheminf:CHEMINF_000200+: #cheminf:has-attribute
    - StartSubstance 
    - Smiles 
    - StandardInchikey
    - StandardInchi
    - cas: <C00000001#cas> 
  - sio:SIO_000255*:
    - Annotation
    - AnnotationMA
  - dcterms:isReferencedBy*:          
    - Reference
    - ReferenceMA
- MolFile <C00000001#x-mdl-molfile>:
  - rdf:type: cheminf:CHEMINF_000058
  - dcterms:format:
    - format_molfile: <nrn:mimetype:chemical/x-mdl-molfile>
  - rdfs:seeAlso:
    - xref_molfile: <https://mb.metabolomics.jp/wiki/Mol:C00000001>
- CDXfile <C00000001#x-chemdraw>:
  - rdf:type: mb:CDXfile
  - dcterms:format:
    - format_cdxfile: <nrn:mimetype:chemical/x-chemdraw>
  - rdfs:seeAlso:
    - xref_cdxfile: <https://mb.metabolomics.jp/wiki/File:C00000001.cdx>
- Gif <C00000001#gif>: 
  - rdf:type: mb:SDfile
  - dcterms:format:
    - format_gif: <nrn:mimetype:image/gif>
  - rdfs:seeAlso:
    - xref_gif: <https://mb.metabolomics.jp/wiki/File:C00000001.gif>
- MolecularFormula <C00000001#molecular_formula>:
  - rdf:type: cheminf:CHEMINF_000042
  - sio:SIO_000300:
    - molecular_formula2: "C19H24O6"
- Names <C00000001#names>:
  - rdf:type: cheminf:CHEMINF_000043
  - sio:SIO_000300:
    - names2: "Gibberellin A1;GA1"
- MolecularWeight <C00000001#molecular_weight>: 
  - rdf:type: cheminf:CHEMINF_000334
  - sio:SIO_000300:
    - value_mw: '"348.15728849094"^^xsd:double'
  - sio:SIO_000221:
    - unit_mw: obo:UO_0000055 # has unit
- Smiles <C00000001#smiles>:
  - rdf:type: cheminf:CHEMINF_000018
  - sio:SIO_000300:
    - value_smiles: "C1[C@@H]([C@@]2([C@@H]3[C@@](C1)([C@H]1[C@@]4([C@H]3C(=O)O)C[C@@](CC1)(C(=C)C4)O)OC2=O)C)O"
- StandardInchikey <C00000001#standard_inchikey>:
  - rdf:type: cheminf:CHEMINF_000059
  - sio:SIO_000300:
    - value_inchikey: "JLJLRLWOEMWYQK-BKYUDGNBNA-N"
  - rdfs:seeAlso:
    - xref_inchikey: <http://identifiers.org/inchikey/JLJLRLWOEMWYQK-BKYUDGNBNA-N>
- StandardInchi <C00000001#standard_inchi>:
  - rdf:type: cheminf:CHEMINF_000113
  - sio:SIO_000300:
    - value_inchi: "InChI=1S/C19H24O6/c1-9-7-17-8-18(9,24)5-3-10(17)19-6-4-11(20)16(2,15(23)25-19)13(19)12(17)14(21)22/h10-13,20,24H,1,3-8H2,2H3,(H,21,22)/t10-,11+,12-,13-,16-,17+,18+,19-/m1/s1"
  - rdfs:seeAlso:
    - xref_inchi: <http://identifiers.org/inchi/InChI=1S/C19H24O6/c1-9-7-17-8-18(9,24)5-3-10(17)19-6-4-11(20)16(2,15(23)25-19)13(19)12(17)14(21)22/h10-13,20,24H,1,3-8H2,2H3,(H,21,22)/t10-,11+,12-,13-,16-,17+,18+,19-/m1/s1>
- StartSubstance <C00000001#start_substance>: 
  - rdf:type: mb:Start_substance
  - sio:SIO_000300:
    - start_substance: ""
- Annotation <annotation#18b24176c038147be449f9dc8b9f27aa>:
  - a: mb:KNApSAcKCoreAnnotation
  - mb:sp:
    - sp: "Thlaspi arvense"
  - mb:references:
    - references: "Metzger,Plant Physiol.,80,(1985),396"
  - mb:sp1:
    - sp1: ""
  - mb:family:
    - family: "Cruciferae"
  - mb:kingdom:
    - kingdom: "Plantae"
  - dcterms:isReferencedBy:
    - is_referenced_by: Reference  
  - rdfs:seeAlso:
    - xref_taxid: <http://identifiers.org/taxonomy/13288>   
  - foaf:homepage:
    - mbwiki_species: https://mb.metabolomics.jp/wiki/Species:Thlaspi_arvense
  - sio:SIO_000254:
    - is_annotation_of: KNApSAcKCoreRecord  
- Reference <reference#8428ae5b90797efd5f9d76ef145f1f6f>:
  - a: mb:KNApSAcKReference
  - dc:identifier:
    - pubmed_id: "16664632"
  - dcterms:references:
    - xref_pubmed: <http://identifiers.org/pubmed/16664632>
  - dc:title:
    - dc_title: "Metzger,Plant Physiol.,80,(1985),396"
  - foaf:homepage:
    - mb_wiki_species: <https://mb.metabolomics.jp/wiki/Reference:Metzger,_Plant_Physiol._,_80,_(1985),_396>
