
- KNApSAcKCoreRecord <http://purl.jp/knapsack/C00000001>:
  - a: mb:KNApSAcKCoreRecord
  - dc:identifier:
    - knapsack_id: "C00000001"
  - rdfs:label:
    - rdfs_label: "Gibberellin A1;GA1"
  - mb:fid:
    - knapsack_fid: "C19H24O6_C00000001"
  - foaf:homepage:
    - foaf_homepage: <https://mb.metabolomics.jp/wiki/Compound:C00000001>
  - rdfs:seeAlso:
    - rdfs_seealso: <http://www.knapsackfamily.com/knapsack_core/info.php?sname=C_ID&word=C00000001>
  - sio:SIO_000008+: #sio:has-attribute
    - MolecularFormula
    - Names
    - MolecularWeight     
  - dc:hasPart+:
    - MolFile
    - ChemDraw
    - Gif
  - cheminf:CHEMINF_000200+: #cheminf:has-attribute
    - StartSubstance 
    - Smiles 
    - StandardInchikey
    - StandardInchi
    - cas: <C00000001#cas> 
  - sio:SIO_000255*:
    - has_annotation: Annotation
  - dcterms:isReferencedBy*:          
    - core_is_referenced_by: Reference
- MolFile <C00000001#x-mdl-molfile>:
  - rdf:type: cheminf:CHEMINF_000058
  - dcterms:format:
    - format_molfile: <nrn:mimetype:chemical/x-mdl-molfile>
  - rdfs:seeAlso:
    - xref_molfile: <https://mb.metabolomics.jp/wiki/Mol:C00000001>
- CDXfile <C00000001#x-chemdraw>:
  - rdf:type: mb:CDXfile
  - dcterms:format:
    - format_cdxfile: <nrn:mimetype:chemical/x-chemdraw>
  - rdfs:seeAlso:
    - xref_cdxfile: <https://mb.metabolomics.jp/wiki/File:C00000001.cdx>
- Gif <C00000001#gif>: 
  - rdf:type: mb:SDfile
  - dcterms:format:
    - format_gif: <nrn:mimetype:image/gif>
  - rdfs:seeAlso:
    - xref_gif: <https://mb.metabolomics.jp/wiki/File:C00000001.gif>
- MolecularFormula <C00000001#molecular_formula>:
  - rdf:type: cheminf:CHEMINF_000042
  - sio:SIO_000300:
    - molecular_formula2: "C19H24O6"
- Names <C00000001#names>:
  - rdf:type: cheminf:CHEMINF_000043
  - sio:SIO_000300:
    - names2: "Gibberellin A1;GA1"
- MolecularWeight <C00000001#molecular_weight>: 
  - rdf:type: cheminf:CHEMINF_000334
  - sio:SIO_000300:
    - value_mw: '"348.15728849094"^^xsd:double'
  - sio:SIO_000221:
    - unit_mw: obo:UO_0000055 # has unit
- Smiles <C00000001#smiles>:
  - rdf:type: cheminf:CHEMINF_000018
  - sio:SIO_000300:
    - value_smiles: "C1[C@@H]([C@@]2([C@@H]3[C@@](C1)([C@H]1[C@@]4([C@H]3C(=O)O)C[C@@](CC1)(C(=C)C4)O)OC2=O)C)O"
- StandardInchikey <C00000001#standard_inchikey>:
  - rdf:type: cheminf:CHEMINF_000059
  - sio:SIO_000300:
    - value_inchikey: "JLJLRLWOEMWYQK-BKYUDGNBNA-N"
  - rdfs:seeAlso:
    - xref_inchikey: <http://identifiers.org/inchikey/JLJLRLWOEMWYQK-BKYUDGNBNA-N>
- StandardInchi <C00000001#standard_inchi>:
  - rdf:type: cheminf:CHEMINF_000113
  - sio:SIO_000300:
    - value_inchi: "InChI=1S/C19H24O6/c1-9-7-17-8-18(9,24)5-3-10(17)19-6-4-11(20)16(2,15(23)25-19)13(19)12(17)14(21)22/h10-13,20,24H,1,3-8H2,2H3,(H,21,22)/t10-,11+,12-,13-,16-,17+,18+,19-/m1/s1"
  - rdfs:seeAlso:
    - xref_inchi: <http://identifiers.org/inchi/InChI=1S/C19H24O6/c1-9-7-17-8-18(9,24)5-3-10(17)19-6-4-11(20)16(2,15(23)25-19)13(19)12(17)14(21)22/h10-13,20,24H,1,3-8H2,2H3,(H,21,22)/t10-,11+,12-,13-,16-,17+,18+,19-/m1/s1>
- StartSubstance <C00000001#start_substance>: 
  - rdf:type: mb:Start_substance
  - sio:SIO_000300:
    - start_substance: ""
- Annotation <annotation#18b24176c038147be449f9dc8b9f27aa>:
  - a: mb:KNApSAcKCoreAnnotation
  - mb:sp:
    - sp: "Thlaspi arvense"
  - mb:references:
    - references: "Metzger,Plant Physiol.,80,(1985),396"
  - mb:sp1:
    - sp1: ""
  - mb:family:
    - family: "Cruciferae"
  - mb:kingdom:
    - kingdom: "Plantae"
  - dcterms:isReferencedBy:
    - is_referenced_by: Reference  
  - rdfs:seeAlso:
    - xref_taxid: <http://identifiers.org/taxonomy/13288>   
  - foaf:homepage:
    - mbwiki_species: https://mb.metabolomics.jp/wiki/Species:Thlaspi_arvense
  - sio:SIO_000254:
    - is_annotation_of: KNApSAcKCoreRecord  
- Reference <reference#8428ae5b90797efd5f9d76ef145f1f6f>:
  - a: mb:KNApSAcKReference
  - dc:identifier:
    - pubmed_id: "16664632"
  - dcterms:references:
    - xref_pubmed: <http://identifiers.org/pubmed/16664632>
  - dc:title:
    - dc_title: "Metzger,Plant Physiol.,80,(1985),396"
  - foaf:homepage:
    - mb_wiki_species: <https://mb.metabolomics.jp/wiki/Reference:Metzger,_Plant_Physiol._,_80,_(1985),_396>
